### ISSUE TITLE
Restarts

### ISSUE THREAD

**Issue by nickykitchingman** [nickykitchingman/orcaflex-webinterface#11]
### Feature

Some jobs in OrcaFlex depend on another job having been completed, these are called **Restarts**, due to starting off where another job finished.
This requires them to be run in order, i.e. only start children after their parents have completed.
This is currently possible, by starting each job manually after a dependent has _successfully_ completed.

Ideally, the jobs would automatically be run in order with the server having done an analysis on submission.
A job without a parent should clearly not be permitted to start.

### Tasks

- [ ] Recognise a restart model
- [ ] Analyse the dependency tree of restarts when uploading a job
- [ ] Schedule child jobs only when parent jobs are in a **completed** state
- [ ] Only allow child jobs to be set to **pending** if parent is in a complete or **running** state
