### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by nickykitchingman** [nickykitchingman/orcaflex-webinterface#15]
### Feature

The only method of examining a simulation is by downloading it, then opening it in OrcaFlex or using a the OrcFxAPI.

A very useful feature, as the simulation file is in the cloud, would be to extract results and display them to the user.
This could be done on a separate **_results_** page.

### Tasks

- [ ] Investigate extracting _results_ of a completed job
- [ ] Decide on a method of transferring them to the **React** application
- [ ] Create a new **_results_** page to display the data
- [ ] Present the summaries to the user
