### ISSUE TITLE
More actions

### ISSUE THREAD

**Issue by nickykitchingman** [nickykitchingman/orcaflex-webinterface#3]
### Feature
Currently there are 2 actions specific to a job: **Run** and **Download**.
There are another 4 actions tied to all uploaded jobs: **Clear**, **Stop**, **Run Pending** and **Run all**.

Ideally each job should have more functionality, and the common actions should also be applicable to a selection of jobs.
A good example is a **pause** button.

### Tasks
- [ ] Add more job specific actions
- [ ] Add more common actions
- [ ] Apply common to a user selection
