### ISSUE TITLE
Post calculations

### ISSUE THREAD

**Issue by nickykitchingman** [nickykitchingman/orcaflex-webinterface#5]
### Feature

Post calculations are python scripts that allow custom behaviour during a simulation, such as a model of a motor.
These can be either embedded into a **.dat** file or linked to an external python file.
There is currently no support for this.

Post calculation actions should be permitted, with their outputs visible to the user.
Any external files will need to be uploaded alongside their corresponding **.dat** files.
Perhaps an auto detection for this on upload would be handy, or at least validation.

### Tasks
- [ ] Allow embedded post calculations to be run, either automatically or separately to the simulation
- [ ] Show the output to the user, including errors
- [ ] Provide support for external post calculation scripts
