### ISSUE TITLE
Makeover

### ISSUE THREAD

**Issue by nickykitchingman** [nickykitchingman/orcaflex-webinterface#7]
### Feature

The current layout and style is hopefully fairly intuitive, but there is definitely room for improvement.

The colour scheme can easily be changed, along with default styles for all the html elements.
The **_Upload_** page is horrible, a drag and drop file placement would be much nicer.
More tabs could be useful, or at least sub navigation within pages, especially **_Process_**.

### Tasks

- [ ] Replace the **_Upload_** system
- [ ] Group the jobs in **_Process_** in some way
- [ ] Improve the visuals of the website
