### ISSUE TITLE
Job window

### ISSUE THREAD

**Issue by nickykitchingman** [nickykitchingman/orcaflex-webinterface#8]
### Feature

The details of a job are currently limited to its status and any progress messages.

It would be useful to see more information about a particular job, both about the file and its progress.
This could be in the form of a **Job window**, which shows the currently selected job(s), from which the user can run the job.

### Tasks

- [ ] Create a **Job window**
- [ ] Show details of the _selected_ job
- [ ] Provide appropriate actions depending on the _state_ and _type_ of job
