### ISSUE TITLE
Thread queue

### ISSUE THREAD

**Issue by nickykitchingman** [nickykitchingman/orcaflex-webinterface#9]
### Feature

At the moment when jobs are submitted, a thread is spawned for each one and left to complete.
This could mean an infinite number of threads could be created, which is silly.

A better solution would be to add the jobs to a working queue, and a pool of threads or processes pick up the tasks when ready.
[`concurrent.futures`](https://docs.python.org/3/library/concurrent.futures.html) may be a good place to start.

### Tasks

- [ ] Construct a plan for handling jobs on the server
- [ ] Separate the submission from the processing
- [ ] Limit the number of concurrent jobs
